'use client'

import { useState, useEffect } from 'react'
import { generateInvoiceNumber } from '@/utils/invoiceNumber'

interface Project {
  id: string;
  name: string;
  type: 'farm' | 'prime' | 'new';
  status: 'active' | 'completed' | 'pending';
  client: string;
  amount: number;
}

interface BillingItem {
  id: string;
  summary: string;
  unitPrice: number;
  quantity: number;
  amount: number;
  remarks: string;
}

interface BillingCreateModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedProject?: Project;
  projects: Project[];
  onBillingApplicationComplete?: (billingData: any) => void;
}

export default function BillingCreateModal({ 
  isOpen, 
  onClose, 
  selectedProject, 
  projects,
  onBillingApplicationComplete
}: BillingCreateModalProps) {
  const [formData, setFormData] = useState({
    projectId: selectedProject?.id || '',
    projectName: selectedProject?.name || '',
    clientName: selectedProject?.client || '',
    billingNumber: '',
    billingDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    taxRate: 10,
    notes: '',
    items: [
      {
        id: '1',
        summary: '',
        unitPrice: 0,
        quantity: 1,
        amount: 0,
        remarks: ''
      }
    ] as BillingItem[]
  });

  const [projectSelectionMode, setProjectSelectionMode] = useState<'existing' | 'new'>(
    selectedProject ? 'existing' : 'new'
  );
  const [showProjectList, setShowProjectList] = useState(false);
  const [showEmailPreview, setShowEmailPreview] = useState(false);
  const [showFinalConfirm, setShowFinalConfirm] = useState(false);
  const [applicantComment, setApplicantComment] = useState('');

  useEffect(() => {
    if (selectedProject) {
      // 請求番号を自動生成
      const autoGeneratedInvoiceNumber = generateInvoiceNumber(
        selectedProject.type,
        selectedProject.client,
        new Date()
      );
      
      setFormData(prev => ({
        ...prev,
        projectId: selectedProject.id,
        projectName: selectedProject.name,
        clientName: selectedProject.client,
        amount: selectedProject.amount,
        billingNumber: autoGeneratedInvoiceNumber
      }));
      setProjectSelectionMode('existing');
    }
  }, [selectedProject]);

  const handleInputChange = (field: string, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // 請求項目の追加
  const addBillingItem = () => {
    const newItem: BillingItem = {
      id: Date.now().toString(),
      summary: '',
      unitPrice: 0,
      quantity: 1,
      amount: 0,
      remarks: ''
    };
    setFormData(prev => ({
      ...prev,
      items: [...prev.items, newItem]
    }));
  };

  // 請求項目の削除
  const removeBillingItem = (itemId: string) => {
    if (formData.items.length > 1) {
      setFormData(prev => ({
        ...prev,
        items: prev.items.filter(item => item.id !== itemId)
      }));
    }
  };

  // 請求項目の更新
  const updateBillingItem = (itemId: string, field: keyof BillingItem, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      items: prev.items.map(item => {
        if (item.id === itemId) {
          const updatedItem = { ...item, [field]: value };
          // 金額を自動計算
          if (field === 'unitPrice' || field === 'quantity') {
            updatedItem.amount = calculateItemAmount(updatedItem);
          }
          return updatedItem;
        }
        return item;
      })
    }));
  };

  const handleProjectSelect = (project: Project) => {
    // 請求番号を自動生成
    const autoGeneratedInvoiceNumber = generateInvoiceNumber(
      project.type,
      project.client,
      new Date()
    );
    
    setFormData(prev => ({
      ...prev,
      projectId: project.id,
      projectName: project.name,
      clientName: project.client,
      amount: project.amount,
      billingNumber: autoGeneratedInvoiceNumber
    }));
    setProjectSelectionMode('existing');
    setShowProjectList(false);
  };

  // メール本文を生成
  const generateEmailContent = () => {
    const currentUser = getCurrentUser();
    const totalAmount = calculateTotalAmount();
    
    return {
      subject: `【${formData.clientName}】請求書の件`,
      body: `${formData.clientName} 担当者様

平素より格別のご高配を賜り、厚く御礼申し上げます。

この度、${formData.projectName}に関する請求書を発行いたしましたので、ご連絡申し上げます。

【請求書詳細】
請求書番号: ${formData.billingNumber}
請求日: ${formData.billingDate}
請求金額: ${formatCurrency(totalAmount)}（税込）

【請求内容】
${formData.items.map(item => `・${item.summary}: ${formatCurrency(item.amount)}`).join('\n')}

合計金額: ${formatCurrency(totalAmount)}（税込）

請求書の詳細は添付ファイルをご確認ください。

ご不明な点がございましたら、お気軽にお問い合わせください。

今後ともよろしくお願いいたします。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
株式会社フェスタル
担当: ${currentUser.name}
TEL: 03-1234-5678
Email: ${currentUser.email}`,
      to: `${formData.clientName.toLowerCase().replace(/\s+/g, '')}@example.com`,
      cc: ''
    };
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // メール本文プレビューを表示
    setShowEmailPreview(true);
  };

  // 担当者情報を取得（ログインユーザー）
  const getCurrentUser = () => {
    return {
      name: '田中太郎',
      email: 'tanaka@festal.co.jp',
      department: '営業部'
    };
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('ja-JP', {
      style: 'currency',
      currency: 'JPY'
    }).format(amount);
  };

  // 請求項目の計算
  const calculateItemAmount = (item: BillingItem) => {
    return item.unitPrice * item.quantity;
  };

  const calculateSubtotal = () => {
    return formData.items.reduce((sum, item) => sum + calculateItemAmount(item), 0);
  };

  const calculateTaxAmount = () => {
    return Math.round(calculateSubtotal() * (formData.taxRate / 100));
  };

  const calculateTotalAmount = () => {
    return calculateSubtotal() + calculateTaxAmount();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full mx-4 max-h-[90vh] overflow-y-auto">
        <div className="px-6 py-4 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold text-gray-900">請求書作成</h2>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="px-6 py-4">
          {/* 案件情報セクション */}
          <div className="mb-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">案件情報</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  案件選択方法
                </label>
                <div className="flex space-x-4">
                  <label className="flex items-center">
                    <input
                      type="radio"
                      value="existing"
                      checked={projectSelectionMode === 'existing'}
                      onChange={(e) => setProjectSelectionMode(e.target.value as 'existing' | 'new')}
                      className="mr-2"
                    />
                    既存案件から選択
                  </label>
                  <label className="flex items-center">
                    <input
                      type="radio"
                      value="new"
                      checked={projectSelectionMode === 'new'}
                      onChange={(e) => setProjectSelectionMode(e.target.value as 'existing' | 'new')}
                      className="mr-2"
                    />
                    新規案件入力
                  </label>
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  担当者
                </label>
                <input
                  type="text"
                  value={getCurrentUser().name}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                  readOnly
                />
              </div>
            </div>

            {projectSelectionMode === 'existing' && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    案件選択
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={formData.projectName}
                      onChange={(e) => handleInputChange('projectName', e.target.value)}
                      onClick={() => setShowProjectList(true)}
                      placeholder="案件を選択してください"
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      readOnly
                    />
                    {showProjectList && (
                      <div className="absolute z-10 w-full mt-1 bg-white border border-gray-300 rounded-md shadow-lg max-h-60 overflow-y-auto">
                        {projects.map((project) => (
                          <div
                            key={project.id}
                            onClick={() => handleProjectSelect(project)}
                            className="px-3 py-2 hover:bg-gray-100 cursor-pointer border-b border-gray-200 last:border-b-0"
                          >
                            <div className="flex items-center justify-between">
                              <div>
                                <div className="font-medium">{project.name}</div>
                                <div className="text-sm text-gray-600">{project.client}</div>
                              </div>
                              <div className="text-xs">
                                {project.type === 'farm' && (
                                  <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                                    ファーム案件
                                  </span>
                                )}
                                {project.type === 'prime' && (
                                  <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                                    プライム案件
                                  </span>
                                )}
                                {project.type === 'new' && (
                                  <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
                                    新規作成
                                  </span>
                                )}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    クライアント名
                  </label>
                  <input
                    type="text"
                    value={formData.clientName}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                    readOnly
                  />
                </div>
              </div>
            )}

            {projectSelectionMode === 'new' && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    案件名 <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.projectName}
                    onChange={(e) => handleInputChange('projectName', e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    クライアント名 <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.clientName}
                    onChange={(e) => {
                      handleInputChange('clientName', e.target.value);
                      // クライアント名が入力されたら請求番号を自動生成
                      if (e.target.value.trim()) {
                        const autoGeneratedInvoiceNumber = generateInvoiceNumber(
                          'new', // 新規作成は業務改善として扱う
                          e.target.value,
                          new Date()
                        );
                        handleInputChange('billingNumber', autoGeneratedInvoiceNumber);
                      }
                    }}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  />
                </div>
              </div>
            )}
          </div>

          {/* 請求書詳細セクション */}
          <div className="mb-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">
              請求書詳細
              {selectedProject && (
                <span className="ml-2 text-sm">
                  {selectedProject.type === 'farm' && (
                    <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                      ファーム案件
                    </span>
                  )}
                  {selectedProject.type === 'prime' && (
                    <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                      プライム案件
                    </span>
                  )}
                  {selectedProject.type === 'new' && (
                    <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
                      新規作成
                    </span>
                  )}
                </span>
              )}
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  請求書番号 <span className="text-red-500">*</span>
                  <span className="ml-2 text-xs text-gray-500">（自動生成）</span>
                </label>
                <input
                  type="text"
                  value={formData.billingNumber}
                  onChange={(e) => handleInputChange('billingNumber', e.target.value)}
                  placeholder="自動生成されます"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-gray-50"
                  required
                  readOnly
                />
                <p className="mt-1 text-xs text-gray-600">
                  フォーマット: YYYYMMDDSSCC
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  請求日 <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  value={formData.billingDate}
                  onChange={(e) => handleInputChange('billingDate', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  支払期限 <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  value={formData.dueDate}
                  onChange={(e) => handleInputChange('dueDate', e.target.value)}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>
          </div>

          {/* 請求項目セクション */}
          <div className="mb-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-medium text-gray-900">請求項目</h3>
              <button
                type="button"
                onClick={addBillingItem}
                className="px-3 py-1 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
              >
                項目を追加
              </button>
            </div>
            
            <div className="overflow-x-auto">
              <table className="min-w-full border border-gray-300">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="border border-gray-300 px-3 py-2 text-left text-sm font-medium text-gray-700">摘要</th>
                    <th className="border border-gray-300 px-3 py-2 text-left text-sm font-medium text-gray-700">単価</th>
                    <th className="border border-gray-300 px-3 py-2 text-left text-sm font-medium text-gray-700">数量</th>
                    <th className="border border-gray-300 px-3 py-2 text-left text-sm font-medium text-gray-700">金額</th>
                    <th className="border border-gray-300 px-3 py-2 text-left text-sm font-medium text-gray-700">備考</th>
                    <th className="border border-gray-300 px-3 py-2 text-left text-sm font-medium text-gray-700">操作</th>
                  </tr>
                </thead>
                <tbody>
                  {formData.items.map((item, index) => (
                    <tr key={item.id}>
                      <td className="border border-gray-300 px-3 py-2">
                        <input
                          type="text"
                          value={item.summary}
                          onChange={(e) => updateBillingItem(item.id, 'summary', e.target.value)}
                          className="w-full px-2 py-1 border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                          placeholder="摘要を入力"
                        />
                      </td>
                      <td className="border border-gray-300 px-3 py-2">
                        <input
                          type="number"
                          value={item.unitPrice}
                          onChange={(e) => updateBillingItem(item.id, 'unitPrice', Number(e.target.value))}
                          className="w-full px-2 py-1 border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                          placeholder="0"
                        />
                      </td>
                      <td className="border border-gray-300 px-3 py-2">
                        <input
                          type="number"
                          value={item.quantity}
                          onChange={(e) => updateBillingItem(item.id, 'quantity', Number(e.target.value))}
                          className="w-full px-2 py-1 border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                          placeholder="1"
                        />
                      </td>
                      <td className="border border-gray-300 px-3 py-2">
                        <input
                          type="number"
                          value={item.amount}
                          className="w-full px-2 py-1 border border-gray-300 rounded bg-gray-50"
                          readOnly
                        />
                      </td>
                      <td className="border border-gray-300 px-3 py-2">
                        <input
                          type="text"
                          value={item.remarks}
                          onChange={(e) => updateBillingItem(item.id, 'remarks', e.target.value)}
                          className="w-full px-2 py-1 border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                          placeholder="備考"
                        />
                      </td>
                      <td className="border border-gray-300 px-3 py-2">
                        {formData.items.length > 1 && (
                          <button
                            type="button"
                            onClick={() => removeBillingItem(item.id)}
                            className="px-2 py-1 text-xs bg-red-600 text-white rounded hover:bg-red-700 transition-colors"
                          >
                            削除
                          </button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* 税区分・合計セクション */}
          <div className="mb-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">税区分</h3>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="mb-4">
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      税率 (%)
                    </label>
                    <input
                      type="number"
                      value={formData.taxRate}
                      onChange={(e) => handleInputChange('taxRate', Number(e.target.value))}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>
              </div>
              
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">合計</h3>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-gray-600">小計:</span>
                      <span className="font-medium">{formatCurrency(calculateSubtotal())}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">消費税 ({formData.taxRate}%):</span>
                      <span className="font-medium">{formatCurrency(calculateTaxAmount())}</span>
                    </div>
                    <div className="flex justify-between text-lg font-semibold border-t pt-2">
                      <span>合計:</span>
                      <span className="text-blue-600">{formatCurrency(calculateTotalAmount())}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>



          {/* アクションボタン */}
          <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
            >
              キャンセル
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
            >
              メール本文プレビュー
            </button>
          </div>
        </form>
      </div>

      {/* メール本文プレビューモーダル */}
      {showEmailPreview && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full mx-4 max-h-[90vh] overflow-y-auto">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-semibold text-gray-900">メール本文プレビュー</h2>
                <button
                  onClick={() => setShowEmailPreview(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="px-6 py-4">
              <div className="space-y-6">
                {/* メール設定 */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">メール設定</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">宛先</label>
                      <input
                        type="email"
                        value={generateEmailContent().to}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                        readOnly
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">CC</label>
                      <input
                        type="email"
                        value={generateEmailContent().cc}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md"
                        placeholder="CCアドレス（任意）"
                      />
                    </div>
                  </div>
                </div>

                {/* メール本文 */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">メール本文</h3>
                  <div className="space-y-3">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">件名</label>
                      <input
                        type="text"
                        value={generateEmailContent().subject}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">本文</label>
                      <textarea
                        value={generateEmailContent().body}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md"
                        rows={15}
                        readOnly
                      />
                    </div>
                  </div>
                </div>

                {/* アクションボタン */}
                <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={() => setShowEmailPreview(false)}
                    className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                  >
                    戻る
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setShowEmailPreview(false);
                      setShowFinalConfirm(true);
                    }}
                    className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors"
                  >
                    経理申請
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 最終確認モーダル */}
      {showFinalConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full mx-4">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-semibold text-gray-900">経理申請確認</h2>
                <button
                  onClick={() => setShowFinalConfirm(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="px-6 py-4">
              <div className="space-y-6">
                {/* 請求書情報 */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">請求書情報</h3>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="text-gray-600">請求書番号:</span>
                      <span className="ml-2 font-medium">{formData.billingNumber}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">案件名:</span>
                      <span className="ml-2 font-medium">{formData.projectName}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">クライアント:</span>
                      <span className="ml-2 font-medium">{formData.clientName}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">請求金額:</span>
                      <span className="ml-2 font-medium">{formatCurrency(calculateTotalAmount())}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">申請者:</span>
                      <span className="ml-2 font-medium">{getCurrentUser().name}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">申請日:</span>
                      <span className="ml-2 font-medium">{new Date().toLocaleDateString('ja-JP')}</span>
                    </div>
                  </div>
                </div>

                {/* 申請者コメント */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">申請者コメント</h3>
                  <textarea
                    value={applicantComment}
                    onChange={(e) => setApplicantComment(e.target.value)}
                    placeholder="申請に関するコメントがあれば入力してください（任意）"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    rows={3}
                  />
                </div>

                {/* アクションボタン */}
                <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={() => setShowFinalConfirm(false)}
                    className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                  >
                    キャンセル
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      // 経理申請処理
                      const billingData = {
                        ...formData,
                        totalAmount: calculateTotalAmount(),
                        subtotal: calculateSubtotal(),
                        taxAmount: calculateTaxAmount(),
                        items: formData.items.map(item => ({
                          ...item,
                          amount: calculateItemAmount(item)
                        })),
                        emailContent: generateEmailContent(),
                        applicantComment: applicantComment,
                        appliedAt: new Date().toISOString(),
                        appliedBy: getCurrentUser().name
                      };
                      
                      // 親コンポーネントに経理申請完了を通知
                      if (onBillingApplicationComplete) {
                        onBillingApplicationComplete(billingData);
                      }
                      
                      setShowFinalConfirm(false);
                      onClose();
                    }}
                    className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors"
                  >
                    請求を確定して経理申請
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
} 