'use client'

import { useState, useEffect } from 'react'
import { generateInvoiceNumber } from '@/utils/invoiceNumber'
import { useEmailTemplates } from '@/contexts/EmailTemplateContext'

interface Project {
  id: string;
  name: string;
  type: 'farm' | 'prime' | 'new';
  status: 'active' | 'completed' | 'pending';
  client: string;
  amount: number;
}

interface BillingItem {
  id: string;
  summary: string;
  unitPrice: number;
  quantity: number;
  amount: number;
  remarks: string;
}

interface BillingCreateModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedProject?: Project;
  projects: Project[];
  onBillingApplicationComplete?: (billingData: any) => void;
}

export default function BillingCreateModal({ 
  isOpen, 
  onClose, 
  selectedProject, 
  projects,
  onBillingApplicationComplete
}: BillingCreateModalProps) {
  const [activeTab, setActiveTab] = useState<'billing' | 'email'>('billing');
  const [showFinalConfirm, setShowFinalConfirm] = useState(false);
  const [showErrorModal, setShowErrorModal] = useState(false);
  const [errorMessages, setErrorMessages] = useState<string[]>([]);
  const [applicantComment, setApplicantComment] = useState('');
  const [formData, setFormData] = useState({
    projectId: selectedProject?.id || '',
    projectName: selectedProject?.name || '',
    clientName: selectedProject?.client || '',
    billingNumber: '',
    billingDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    taxRate: 10,
    notes: '',
    emailContent: {
      subject: '',
      body: '',
      to: '',
      cc: '',
      bcc: ''
    },
    items: [
      {
        id: '1',
        summary: '',
        unitPrice: 0,
        quantity: 1,
        amount: 0,
        remarks: ''
      }
    ] as BillingItem[]
  });

  const [projectSelectionMode, setProjectSelectionMode] = useState<'existing' | 'new'>(
    selectedProject ? 'existing' : 'new'
  );
  const [showProjectList, setShowProjectList] = useState(false);

  // EmailTemplateContext繧剃ｽｿ逕ｨ
  const { templates } = useEmailTemplates();

  // 蛻晄悄繝輔か繝ｼ繝繝・・繧ｿ繧堤函謌舌☆繧矩未謨ｰ
  const getInitialFormData = (project?: Project) => {
    const autoGeneratedInvoiceNumber = project ? generateInvoiceNumber(
      project.type,
      project.client,
      new Date()
    ) : '';

    return {
      projectId: project?.id || '',
      projectName: project?.name || '',
      clientName: project?.client || '',
      billingNumber: autoGeneratedInvoiceNumber,
      billingDate: new Date().toISOString().split('T')[0],
      dueDate: '',
      taxRate: 10,
      notes: '',
      emailContent: {
        subject: '',
        body: '',
        to: '',
        cc: '',
        bcc: ''
      },
      items: [
        {
          id: '1',
          summary: '',
          unitPrice: 0,
          quantity: 1,
          amount: 0,
          remarks: ''
        }
      ] as BillingItem[]
    };
  };

  useEffect(() => {
    if (isOpen) {
      // 繝｢繝ｼ繝繝ｫ縺碁幕縺九ｌ繧九◆縺ｳ縺ｫ繝輔か繝ｼ繝繝・・繧ｿ繧偵Μ繧ｻ繝・ヨ
      const initialData = getInitialFormData(selectedProject);
      setFormData(initialData);
      setActiveTab('billing');
      setShowFinalConfirm(false);
      setShowErrorModal(false);
      setErrorMessages([]);
      setApplicantComment('');
      setProjectSelectionMode(selectedProject ? 'existing' : 'new');
      setShowProjectList(false);
    }
  }, [isOpen, selectedProject]);

  useEffect(() => {
    if (selectedProject && isOpen) {
      const autoGeneratedInvoiceNumber = generateInvoiceNumber(
        selectedProject.type,
        selectedProject.client,
        new Date()
      );
      
      setFormData(prev => ({
        ...prev,
        projectId: selectedProject.id,
        projectName: selectedProject.name,
        clientName: selectedProject.client,
        amount: selectedProject.amount,
        billingNumber: autoGeneratedInvoiceNumber
      }));
      setProjectSelectionMode('existing');
    }
  }, [selectedProject, isOpen]);

  const handleInputChange = (field: string, value: string | number | any) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const addBillingItem = () => {
    const newItem: BillingItem = {
      id: Date.now().toString(),
      summary: '',
      unitPrice: 0,
      quantity: 1,
      amount: 0,
      remarks: ''
    };
    setFormData(prev => ({
      ...prev,
      items: [...prev.items, newItem]
    }));
  };

  const removeBillingItem = (itemId: string) => {
    if (formData.items.length > 1) {
      setFormData(prev => ({
        ...prev,
        items: prev.items.filter(item => item.id !== itemId)
      }));
    }
  };

  const calculateItemAmount = (item: BillingItem) => {
    return item.unitPrice * item.quantity;
  };

  const updateBillingItem = (itemId: string, field: keyof BillingItem, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      items: prev.items.map(item => {
        if (item.id === itemId) {
          const updatedItem = { ...item, [field]: value };
          if (field === 'unitPrice' || field === 'quantity') {
            updatedItem.amount = calculateItemAmount(updatedItem);
          }
          return updatedItem;
        }
        return item;
      })
    }));
  };

  const handleProjectSelect = (project: Project) => {
    const autoGeneratedInvoiceNumber = generateInvoiceNumber(
      project.type,
      project.client,
      new Date()
    );
    
    setFormData(prev => ({
      ...prev,
      projectId: project.id,
      projectName: project.name,
      clientName: project.client,
      amount: project.amount,
      billingNumber: autoGeneratedInvoiceNumber
    }));
    setProjectSelectionMode('existing');
    setShowProjectList(false);
  };

  const calculateSubtotal = () => {
    return formData.items.reduce((sum, item) => sum + calculateItemAmount(item), 0);
  };

  const calculateTaxAmount = () => {
    return Math.round(calculateSubtotal() * (formData.taxRate / 100));
  };

  const calculateTotalAmount = () => {
    return calculateSubtotal() + calculateTaxAmount();
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('ja-JP', {
      style: 'currency',
      currency: 'JPY'
    }).format(amount);
  };

  const getCurrentUser = () => {
    return {
      name: '逕ｰ荳ｭ螟ｪ驛・,
      email: 'tanaka@festal.co.jp',
      department: '蝟ｶ讌ｭ驛ｨ'
    };
  };

  const generateEmailContent = () => {
    const currentUser = getCurrentUser();
    const totalAmount = calculateTotalAmount();
    
    return {
      subject: `縲・{formData.clientName}縲題ｫ区ｱよ嶌縺ｮ莉ｶ`,
      body: `${formData.clientName} 諡・ｽ楢・ｧ・

蟷ｳ邏繧医ｊ譬ｼ蛻･縺ｮ縺秘ｫ倬・繧定ｳ懊ｊ縲∝字縺丞ｾ｡遉ｼ逕ｳ縺嶺ｸ翫￡縺ｾ縺吶・

縺薙・蠎ｦ縲・{formData.projectName}縺ｫ髢｢縺吶ｋ隲区ｱよ嶌繧堤匱陦後＞縺溘＠縺ｾ縺励◆縺ｮ縺ｧ縲√＃騾｣邨｡逕ｳ縺嶺ｸ翫￡縺ｾ縺吶・

縲占ｫ区ｱよ嶌隧ｳ邏ｰ縲・
隲区ｱよ嶌逡ｪ蜿ｷ: ${formData.billingNumber}
隲区ｱよ律: ${formData.billingDate}
隲区ｱる≡鬘・ ${formatCurrency(totalAmount)}・育ｨ手ｾｼ・・

縲占ｫ区ｱょ・螳ｹ縲・
${formData.items.map(item => `繝ｻ${item.summary}: ${formatCurrency(calculateItemAmount(item))}`).join('\n')}

蜷郁ｨ磯≡鬘・ ${formatCurrency(totalAmount)}・育ｨ手ｾｼ・・

隲区ｱよ嶌縺ｮ隧ｳ邏ｰ縺ｯ豺ｻ莉倥ヵ繧｡繧､繝ｫ繧偵＃遒ｺ隱阪￥縺縺輔＞縲・

縺比ｸ肴・縺ｪ轤ｹ縺後＃縺悶＞縺ｾ縺励◆繧峨√♀豌苓ｻｽ縺ｫ縺雁撫縺・粋繧上○縺上□縺輔＞縲・

莉雁ｾ後→繧ゅｈ繧阪＠縺上♀鬘倥＞縺・◆縺励∪縺吶・

笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏≫煤笏・
譬ｪ蠑丈ｼ夂､ｾ繝輔ぉ繧ｹ繧ｿ繝ｫ
諡・ｽ・ ${currentUser.name}
TEL: 03-1234-5678
Email: ${currentUser.email}`,
      to: `${formData.clientName.toLowerCase().replace(/\s+/g, '')}@example.com`,
      cc: formData.emailContent.cc,
      bcc: formData.emailContent.bcc
    };
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setActiveTab('email');
  };

  const handleTemplateSelect = (template: any) => {
    const generatedContent = generateEmailContent();
    setFormData(prev => ({
      ...prev,
      emailContent: {
        subject: template.subject.replace('{clientName}', formData.clientName),
        body: template.body
          .replace('{clientName}', formData.clientName)
          .replace('{projectName}', formData.projectName)
          .replace('{billingNumber}', formData.billingNumber)
          .replace('{billingDate}', formData.billingDate)
          .replace('{totalAmount}', formatCurrency(calculateTotalAmount()))
          .replace('{items}', formData.items.map(item => `繝ｻ${item.summary}: ${formatCurrency(calculateItemAmount(item))}`).join('\n'))
          .replace('{userName}', getCurrentUser().name)
          .replace('{userEmail}', getCurrentUser().email),
        to: generatedContent.to,
        cc: formData.emailContent.cc,
        bcc: formData.emailContent.bcc
      }
    }));
  };

  // 繝舌Μ繝・・繧ｷ繝ｧ繝ｳ髢｢謨ｰ
  const validateForm = (): { isValid: boolean; errors: string[] } => {
    const errors: string[] = [];

    // 隲区ｱょ・螳ｹ縺ｮ繝舌Μ繝・・繧ｷ繝ｧ繝ｳ
    if (activeTab === 'billing') {
      if (!formData.projectName.trim()) {
        errors.push('譯井ｻｶ蜷阪・蠢・磯・岼縺ｧ縺・);
      }
      if (!formData.clientName.trim()) {
        errors.push('繧ｯ繝ｩ繧､繧｢繝ｳ繝亥錐縺ｯ蠢・磯・岼縺ｧ縺・);
      }
      if (!formData.billingNumber.trim()) {
        errors.push('隲区ｱよ嶌逡ｪ蜿ｷ縺ｯ蠢・磯・岼縺ｧ縺・);
      }
      if (!formData.billingDate) {
        errors.push('隲区ｱよ律縺ｯ蠢・磯・岼縺ｧ縺・);
      }
      
      // 隲区ｱる・岼縺ｮ繝舌Μ繝・・繧ｷ繝ｧ繝ｳ
      formData.items.forEach((item, index) => {
        if (!item.summary.trim()) {
          errors.push(`隲区ｱる・岼${index + 1}縺ｮ鞫倩ｦ√・蠢・磯・岼縺ｧ縺兪);
        }
        if (item.unitPrice <= 0) {
          errors.push(`隲区ｱる・岼${index + 1}縺ｮ蜊倅ｾ｡縺ｯ0繧医ｊ螟ｧ縺阪＞蛟､繧貞・蜉帙＠縺ｦ縺上□縺輔＞`);
        }
        if (item.quantity <= 0) {
          errors.push(`隲区ｱる・岼${index + 1}縺ｮ謨ｰ驥上・0繧医ｊ螟ｧ縺阪＞蛟､繧貞・蜉帙＠縺ｦ縺上□縺輔＞`);
        }
      });
    }

    // 繝｡繝ｼ繝ｫ蜀・ｮｹ縺ｮ繝舌Μ繝・・繧ｷ繝ｧ繝ｳ
    if (activeTab === 'email') {
      if (!formData.emailContent.to.trim()) {
        errors.push('螳帛・縺ｯ蠢・磯・岼縺ｧ縺・);
      }
      if (!formData.emailContent.subject.trim()) {
        errors.push('莉ｶ蜷阪・蠢・磯・岼縺ｧ縺・);
      }
      if (!formData.emailContent.body.trim()) {
        errors.push('譛ｬ譁・・蠢・磯・岼縺ｧ縺・);
      }
    }

    return { isValid: errors.length === 0, errors };
  };

  // 遒ｺ螳壹・繧ｿ繝ｳ縺ｮ繧ｯ繝ｪ繝・け繝上Φ繝峨Λ繝ｼ
  const handleConfirmClick = () => {
    const validation = validateForm();
    
    if (!validation.isValid) {
      setErrorMessages(validation.errors);
      setShowErrorModal(true);
      return;
    }
    
    setShowFinalConfirm(true);
  };

  // 繝｢繝ｼ繝繝ｫ繧帝哩縺倥ｋ蜃ｦ逅・
  const handleClose = () => {
    // 迥ｶ諷九ｒ繝ｪ繧ｻ繝・ヨ
    setFormData(getInitialFormData());
    setActiveTab('billing');
    setShowFinalConfirm(false);
    setShowErrorModal(false);
    setErrorMessages([]);
    setApplicantComment('');
    setProjectSelectionMode('new');
    setShowProjectList(false);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <>
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div className="bg-white rounded-lg shadow-xl max-w-6xl w-full mx-4 max-h-[90vh] overflow-y-auto">
          <div className="px-6 py-4 border-b border-gray-200">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-semibold text-gray-900">隲区ｱよ嶌菴懈・</h2>
              <button
                onClick={handleClose}
                className="text-gray-400 hover:text-gray-600"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>

          {/* 繧ｿ繝悶リ繝薙ご繝ｼ繧ｷ繝ｧ繝ｳ */}
          <div className="px-6 pt-4">
            <div className="flex border-b border-gray-200 mb-6">
              <button
                type="button"
                onClick={() => setActiveTab('billing')}
                className={`px-4 py-2 text-sm font-medium border-b-2 ${
                  activeTab === 'billing'
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700'
                }`}
              >
                隲区ｱょ・螳ｹ
              </button>
              <button
                type="button"
                onClick={() => setActiveTab('email')}
                className={`px-4 py-2 text-sm font-medium border-b-2 ${
                  activeTab === 'email'
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700'
                }`}
              >
                繝｡繝ｼ繝ｫ蜀・ｮｹ
              </button>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="px-6 pb-4">
            {/* 隲区ｱょ・螳ｹ繧ｿ繝・*/}
            {activeTab === 'billing' && (
              <div className="space-y-6">
                {/* 譯井ｻｶ諠・ｱ繧ｻ繧ｯ繧ｷ繝ｧ繝ｳ */}
                <div className="mb-6">
                  <h3 className="text-lg font-medium text-gray-900 mb-4">譯井ｻｶ諠・ｱ</h3>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        譯井ｻｶ蜷・
                      </label>
                      <input
                        type="text"
                        value={formData.projectName}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                        readOnly
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        繧ｯ繝ｩ繧､繧｢繝ｳ繝亥錐
                      </label>
                      <input
                        type="text"
                        value={formData.clientName}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                        readOnly
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        諡・ｽ楢・
                      </label>
                      <input
                        type="text"
                        value={getCurrentUser().name}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                        readOnly
                      />
                    </div>
                  </div>
                </div>

                {/* 隲区ｱよ嶌隧ｳ邏ｰ繧ｻ繧ｯ繧ｷ繝ｧ繝ｳ */}
                <div className="mb-6">
                  <h3 className="text-lg font-medium text-gray-900 mb-4">
                    隲区ｱよ嶌隧ｳ邏ｰ
                    {selectedProject && (
                      <span className="ml-2 text-sm">
                        {selectedProject.type === 'farm' && (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                            繝輔ぃ繝ｼ繝譯井ｻｶ
                          </span>
                        )}
                        {selectedProject.type === 'prime' && (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                            繝励Λ繧､繝譯井ｻｶ
                          </span>
                        )}
                        {selectedProject.type === 'new' && (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
                            譁ｰ隕丈ｽ懈・
                          </span>
                        )}
                      </span>
                    )}
                  </h3>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        隲区ｱよ嶌逡ｪ蜿ｷ <span className="text-red-500">*</span>
                        <span className="ml-2 text-xs text-gray-500">・郁・蜍慕函謌撰ｼ・/span>
                      </label>
                      <input
                        type="text"
                        value={formData.billingNumber}
                        onChange={(e) => handleInputChange('billingNumber', e.target.value)}
                        placeholder="閾ｪ蜍慕函謌舌＆繧後∪縺・
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-gray-50"
                        required
                        readOnly
                      />
                      <p className="mt-1 text-xs text-gray-600">
                        繝輔か繝ｼ繝槭ャ繝・ YYYYMMDDSSCC
                      </p>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        隲区ｱよ律 <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="date"
                        value={formData.billingDate}
                        onChange={(e) => handleInputChange('billingDate', e.target.value)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        required
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        謾ｯ謇墓悄髯・
                      </label>
                      <input
                        type="date"
                        value={formData.dueDate}
                        onChange={(e) => handleInputChange('dueDate', e.target.value)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                  </div>
                </div>

                {/* 隲区ｱる・岼繧ｻ繧ｯ繧ｷ繝ｧ繝ｳ */}
                <div className="mb-6">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-medium text-gray-900">隲区ｱる・岼</h3>
                    <button
                      type="button"
                      onClick={addBillingItem}
                      className="px-3 py-1 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                    >
                      鬆・岼霑ｽ蜉
                    </button>
                  </div>
                  
                  <div className="space-y-4">
                    {formData.items.map((item, index) => (
                      <div key={item.id} className="p-4 bg-gray-50 rounded-lg">
                        <div className="flex gap-4">
                          <div className="w-64">
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                              鞫倩ｦ・<span className="text-red-500">*</span>
                            </label>
                            <input
                              type="text"
                              required
                              value={item.summary}
                              onChange={(e) => updateBillingItem(item.id, 'summary', e.target.value)}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                              placeholder="鞫倩ｦ√ｒ蜈･蜉・
                            />
                          </div>
                          <div className="w-36">
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                              蜊倅ｾ｡
                            </label>
                            <input
                              type="number"
                              value={item.unitPrice}
                              onChange={(e) => updateBillingItem(item.id, 'unitPrice', Number(e.target.value))}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                              placeholder="0"
                            />
                          </div>
                          <div className="w-16">
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                              謨ｰ驥・
                            </label>
                            <input
                              type="number"
                              value={item.quantity}
                              onChange={(e) => updateBillingItem(item.id, 'quantity', Number(e.target.value))}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                              placeholder="1"
                            />
                          </div>
                          <div className="w-40">
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                              驥鷹｡・
                            </label>
                            <input
                              type="text"
                              value={formatCurrency(calculateItemAmount(item))}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                              readOnly
                            />
                          </div>
                          <div className="flex-1 min-w-0">
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                              蛯呵・
                            </label>
                            <input
                              type="text"
                              value={item.remarks}
                              onChange={(e) => updateBillingItem(item.id, 'remarks', e.target.value)}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                              placeholder="蛯呵・
                            />
                          </div>
                        </div>
                        {formData.items.length > 1 && (
                          <button
                            type="button"
                            onClick={() => removeBillingItem(item.id)}
                            className="mt-2 text-red-600 hover:text-red-800 text-sm"
                          >
                            蜑企勁
                          </button>
                        )}
                      </div>
                    ))}
                  </div>
                </div>

                {/* 遞主玄蛻・・蜷郁ｨ医そ繧ｯ繧ｷ繝ｧ繝ｳ */}
                <div className="mb-6">
                  <h3 className="text-lg font-medium text-gray-900 mb-4">遞主玄蛻・・蜷郁ｨ・/h3>
                  
                  <div className="flex gap-6">
                    <div className="w-48">
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        遞守紫(%)
                      </label>
                      <input
                        type="number"
                        value={formData.taxRate}
                        onChange={(e) => handleInputChange('taxRate', Number(e.target.value))}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        placeholder="10"
                      />
                    </div>
                    
                    <div className="bg-gray-50 rounded-lg p-4 flex-1">
                      <div className="space-y-3">
                        <div className="flex justify-between">
                          <span className="text-gray-600">蟆剰ｨ・</span>
                          <span className="font-medium">{formatCurrency(calculateSubtotal())}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">豸郁ｲｻ遞・{formData.taxRate}%):</span>
                          <span className="font-medium">{formatCurrency(calculateTaxAmount())}</span>
                        </div>
                        <div className="flex justify-between text-lg font-bold text-blue-600 border-t border-gray-200 pt-3">
                          <span>蜷郁ｨ・</span>
                          <span>{formatCurrency(calculateTotalAmount())}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* 繧｢繧ｯ繧ｷ繝ｧ繝ｳ繝懊ち繝ｳ */}
                <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={handleClose}
                    className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                  >
                    繧ｭ繝｣繝ｳ繧ｻ繝ｫ
                  </button>
                  <button
                    type="button"
                    onClick={handleConfirmClick}
                    className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                  >
                    遒ｺ螳・
                  </button>
                </div>
              </div>
            )}

            {/* 繝｡繝ｼ繝ｫ蜀・ｮｹ繧ｿ繝・*/}
            {activeTab === 'email' && (
              <div className="space-y-6">
                {/* 繝｡繝ｼ繝ｫ蜀・ｮｹ */}
                <div>
                  <h3 className="text-md font-medium text-gray-900 mb-4">繝｡繝ｼ繝ｫ蜀・ｮｹ</h3>
                  
                  <div className="space-y-4">
                    {/* 螳帛・ */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        螳帛・ <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="email"
                        required
                        value={formData.emailContent.to}
                        onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, to: e.target.value })}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        placeholder="繝｡繝ｼ繝ｫ繧｢繝峨Ξ繧ｹ繧貞・蜉・
                      />
                    </div>
                    
                    {/* CC 縺ｨ BCC 繧呈ｨｪ荳ｦ縺ｳ縺ｧ驟咲ｽｮ */}
                    <div className="flex gap-4">
                      {/* CC */}
                      <div className="w-36">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          CC
                        </label>
                        <input
                          type="email"
                          value={formData.emailContent.cc}
                          onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, cc: e.target.value })}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          placeholder="CC繝｡繝ｼ繝ｫ繧｢繝峨Ξ繧ｹ"
                        />
                      </div>
                      
                      {/* BCC */}
                      <div className="w-36">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          BCC
                        </label>
                        <input
                          type="email"
                          value={formData.emailContent.bcc}
                          onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, bcc: e.target.value })}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          placeholder="BCC繝｡繝ｼ繝ｫ繧｢繝峨Ξ繧ｹ"
                        />
                      </div>
                    </div>
                    
                    {/* 莉ｶ蜷・*/}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        莉ｶ蜷・<span className="text-red-500">*</span>
                      </label>
                      <input
                        type="text"
                        required
                        value={formData.emailContent.subject}
                        onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, subject: e.target.value })}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        placeholder="繝｡繝ｼ繝ｫ莉ｶ蜷阪ｒ蜈･蜉・
                      />
                    </div>
                    
                    {/* 繝｡繝ｼ繝ｫ譛ｬ譁・*/}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        譛ｬ譁・<span className="text-red-500">*</span>
                      </label>
                      <textarea
                        value={formData.emailContent.body}
                        onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, body: e.target.value })}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        rows={6}
                        placeholder="繝｡繝ｼ繝ｫ譛ｬ譁・ｒ蜈･蜉・
                        required
                      />
                    </div>
                  </div>
                </div>

                {/* 繧｢繧ｯ繧ｷ繝ｧ繝ｳ繝懊ち繝ｳ */}
                <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={() => setActiveTab('billing')}
                    className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                  >
                    謌ｻ繧・
                  </button>
                  <button
                    type="button"
                    onClick={handleConfirmClick}
                    className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                  >
                    遒ｺ螳・
                  </button>
                </div>
              </div>
            )}
          </form>
        </div>
      </div>

      {/* 譛邨ら｢ｺ隱阪Δ繝ｼ繝繝ｫ */}
      {showFinalConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full mx-4">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-end">
                <button
                  onClick={() => setShowFinalConfirm(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="px-6 py-4">
              <div className="space-y-6">
                {/* 遒ｺ隱阪Γ繝・そ繝ｼ繧ｸ */}
                <div className="text-center">
                  <div className="mb-4">
                    <svg className="w-12 h-12 text-blue-600 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <h3 className="text-lg font-medium text-gray-900 mb-2">邨檎炊逕ｳ隲九・遒ｺ隱・/h3>
                    <p className="text-gray-600">
                      縺薙・蜀・ｮｹ縺ｧ邨檎炊諡・ｽ楢・∈逕ｳ隲九＠縺ｦ繧ゅｈ繧阪＠縺・〒縺吶°・・
                    </p>
                  </div>
                </div>

                {/* 逕ｳ隲玖・さ繝｡繝ｳ繝・*/}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">逕ｳ隲玖・さ繝｡繝ｳ繝・/h3>
                  <textarea
                    value={applicantComment}
                    onChange={(e) => setApplicantComment(e.target.value)}
                    placeholder="逕ｳ隲九↓髢｢縺吶ｋ繧ｳ繝｡繝ｳ繝医′縺ゅｌ縺ｰ蜈･蜉帙＠縺ｦ縺上□縺輔＞・井ｻｻ諢擾ｼ・
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    rows={3}
                  />
                </div>

                {/* 繧｢繧ｯ繧ｷ繝ｧ繝ｳ繝懊ち繝ｳ */}
                <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={() => setShowFinalConfirm(false)}
                    className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                  >
                    繧ｭ繝｣繝ｳ繧ｻ繝ｫ
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const billingData = {
                        ...formData,
                        totalAmount: calculateTotalAmount(),
                        subtotal: calculateSubtotal(),
                        taxAmount: calculateTaxAmount(),
                        items: formData.items.map(item => ({
                          ...item,
                          amount: calculateItemAmount(item)
                        })),
                        emailContent: generateEmailContent(),
                        applicantComment: applicantComment,
                        appliedAt: new Date().toISOString(),
                        appliedBy: getCurrentUser().name,
                        status: 'pending'
                      };
                      
                      if (onBillingApplicationComplete) {
                        onBillingApplicationComplete(billingData);
                      }
                      
                      setShowFinalConfirm(false);
                      handleClose();
                    }}
                    className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors"
                  >
                    邨檎炊逕ｳ隲・
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 繧ｨ繝ｩ繝ｼ繝｢繝ｼ繝繝ｫ */}
      {showErrorModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-medium text-gray-900">蜈･蜉帙お繝ｩ繝ｼ</h3>
                <button
                  onClick={() => setShowErrorModal(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="px-6 py-4">
              <div className="space-y-4">
                {/* 繧ｨ繝ｩ繝ｼ繧｢繧､繧ｳ繝ｳ */}
                <div className="text-center">
                  <svg className="w-12 h-12 text-red-600 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
                  </svg>
                  <p className="text-gray-600 mb-4">
                    莉･荳九・鬆・岼繧貞・蜉帙＠縺ｦ縺上□縺輔＞・・
                  </p>
                </div>

                {/* 繧ｨ繝ｩ繝ｼ繝｡繝・そ繝ｼ繧ｸ荳隕ｧ */}
                <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                  <ul className="space-y-2">
                    {errorMessages.map((error, index) => (
                      <li key={index} className="text-red-700 text-sm flex items-start">
                        <span className="text-red-500 mr-2">窶｢</span>
                        {error}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* 繧｢繧ｯ繧ｷ繝ｧ繝ｳ繝懊ち繝ｳ */}
                <div className="flex justify-end pt-4">
                  <button
                    type="button"
                    onClick={() => setShowErrorModal(false)}
                    className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                  >
                    髢峨§繧・
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
} 
