'use client'

import { useState, useEffect } from 'react'
import { generateInvoiceNumber } from '@/utils/invoiceNumber'

interface Project {
  id: string;
  name: string;
  type: 'farm' | 'prime' | 'new';
  status: 'active' | 'completed' | 'pending';
  client: string;
  amount: number;
}

interface BillingItem {
  id: string;
  summary: string;
  unitPrice: number;
  quantity: number;
  amount: number;
  remarks: string;
}

interface BillingCreateModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedProject?: Project;
  projects: Project[];
  onBillingApplicationComplete?: (billingData: any) => void;
}

export default function BillingCreateModal({ 
  isOpen, 
  onClose, 
  selectedProject, 
  projects,
  onBillingApplicationComplete
}: BillingCreateModalProps) {
  const [activeTab, setActiveTab] = useState<'billing' | 'email'>('billing');
  const [formData, setFormData] = useState({
    projectId: selectedProject?.id || '',
    projectName: selectedProject?.name || '',
    clientName: selectedProject?.client || '',
    billingNumber: '',
    billingDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    taxRate: 10,
    notes: '',
    emailContent: {
      subject: '',
      body: '',
      to: '',
      cc: '',
      bcc: ''
    },
    items: [
      {
        id: '1',
        summary: '',
        unitPrice: 0,
        quantity: 1,
        amount: 0,
        remarks: ''
      }
    ] as BillingItem[]
  });

  const [projectSelectionMode, setProjectSelectionMode] = useState<'existing' | 'new'>(
    selectedProject ? 'existing' : 'new'
  );
  const [showProjectList, setShowProjectList] = useState(false);
  const [showFinalConfirm, setShowFinalConfirm] = useState(false);
  const [applicantComment, setApplicantComment] = useState('');

  useEffect(() => {
    if (selectedProject) {
      const autoGeneratedInvoiceNumber = generateInvoiceNumber(
        selectedProject.type,
        selectedProject.client,
        new Date()
      );
      
      setFormData(prev => ({
        ...prev,
        projectId: selectedProject.id,
        projectName: selectedProject.name,
        clientName: selectedProject.client,
        amount: selectedProject.amount,
        billingNumber: autoGeneratedInvoiceNumber
      }));
      setProjectSelectionMode('existing');
    }
  }, [selectedProject]);

  const handleInputChange = (field: string, value: string | number | any) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const addBillingItem = () => {
    const newItem: BillingItem = {
      id: Date.now().toString(),
      summary: '',
      unitPrice: 0,
      quantity: 1,
      amount: 0,
      remarks: ''
    };
    setFormData(prev => ({
      ...prev,
      items: [...prev.items, newItem]
    }));
  };

  const removeBillingItem = (itemId: string) => {
    if (formData.items.length > 1) {
      setFormData(prev => ({
        ...prev,
        items: prev.items.filter(item => item.id !== itemId)
      }));
    }
  };

  const calculateItemAmount = (item: BillingItem) => {
    return item.unitPrice * item.quantity;
  };

  const updateBillingItem = (itemId: string, field: keyof BillingItem, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      items: prev.items.map(item => {
        if (item.id === itemId) {
          const updatedItem = { ...item, [field]: value };
          if (field === 'unitPrice' || field === 'quantity') {
            updatedItem.amount = calculateItemAmount(updatedItem);
          }
          return updatedItem;
        }
        return item;
      })
    }));
  };

  const handleProjectSelect = (project: Project) => {
    const autoGeneratedInvoiceNumber = generateInvoiceNumber(
      project.type,
      project.client,
      new Date()
    );
    
    setFormData(prev => ({
      ...prev,
      projectId: project.id,
      projectName: project.name,
      clientName: project.client,
      amount: project.amount,
      billingNumber: autoGeneratedInvoiceNumber
    }));
    setProjectSelectionMode('existing');
    setShowProjectList(false);
  };

  const calculateSubtotal = () => {
    return formData.items.reduce((sum, item) => sum + calculateItemAmount(item), 0);
  };

  const calculateTaxAmount = () => {
    return Math.round(calculateSubtotal() * (formData.taxRate / 100));
  };

  const calculateTotalAmount = () => {
    return calculateSubtotal() + calculateTaxAmount();
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('ja-JP', {
      style: 'currency',
      currency: 'JPY'
    }).format(amount);
  };

  const getCurrentUser = () => {
    return {
      name: '田中太郎',
      email: 'tanaka@festal.co.jp',
      department: '営業部'
    };
  };

  const generateEmailContent = () => {
    const currentUser = getCurrentUser();
    const totalAmount = calculateTotalAmount();
    
    return {
      subject: `【${formData.clientName}】請求書の件`,
      body: `${formData.clientName} 担当者様

平素より格別のご高配を賜り、厚く御礼申し上げます。

この度、${formData.projectName}に関する請求書を発行いたしましたので、ご連絡申し上げます。

【請求書詳細】
請求書番号: ${formData.billingNumber}
請求日: ${formData.billingDate}
請求金額: ${formatCurrency(totalAmount)}（税込）

【請求内容】
${formData.items.map(item => `・${item.summary}: ${formatCurrency(calculateItemAmount(item))}`).join('\n')}

合計金額: ${formatCurrency(totalAmount)}（税込）

請求書の詳細は添付ファイルをご確認ください。

ご不明な点がございましたら、お気軽にお問い合わせください。

今後ともよろしくお願いいたします。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
株式会社フェスタル
担当: ${currentUser.name}
TEL: 03-1234-5678
Email: ${currentUser.email}`,
      to: `${formData.clientName.toLowerCase().replace(/\s+/g, '')}@example.com`,
      cc: formData.emailContent.cc,
      bcc: formData.emailContent.bcc
    };
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setActiveTab('email');
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-6xl w-full mx-4 max-h-[90vh] overflow-y-auto">
        <div className="px-6 py-4 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold text-gray-900">請求書作成</h2>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* タブナビゲーション */}
        <div className="px-6 pt-4">
          <div className="flex border-b border-gray-200 mb-6">
            <button
              type="button"
              onClick={() => setActiveTab('billing')}
              className={`px-4 py-2 text-sm font-medium border-b-2 ${
                activeTab === 'billing'
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700'
              }`}
            >
              請求内容
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('email')}
              className={`px-4 py-2 text-sm font-medium border-b-2 ${
                activeTab === 'email'
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700'
              }`}
            >
              メール内容
            </button>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="px-6 pb-4">
          {/* 請求内容タブ */}
          {activeTab === 'billing' && (
            <div className="space-y-6">
              {/* 案件情報セクション */}
              <div className="mb-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">案件情報</h3>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      案件名
                    </label>
                    <input
                      type="text"
                      value={formData.projectName}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                      readOnly
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      クライアント名
                    </label>
                    <input
                      type="text"
                      value={formData.clientName}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                      readOnly
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      担当者
                    </label>
                    <input
                      type="text"
                      value={getCurrentUser().name}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                      readOnly
                    />
                  </div>
                </div>
              </div>

              {/* 請求書詳細セクション */}
              <div className="mb-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">
                  請求書詳細
                  {selectedProject && (
                    <span className="ml-2 text-sm">
                      {selectedProject.type === 'farm' && (
                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                          ファーム案件
                        </span>
                      )}
                      {selectedProject.type === 'prime' && (
                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                          プライム案件
                        </span>
                      )}
                      {selectedProject.type === 'new' && (
                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
                          新規作成
                        </span>
                      )}
                    </span>
                  )}
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      請求書番号 <span className="text-red-500">*</span>
                      <span className="ml-2 text-xs text-gray-500">（自動生成）</span>
                    </label>
                    <input
                      type="text"
                      value={formData.billingNumber}
                      onChange={(e) => handleInputChange('billingNumber', e.target.value)}
                      placeholder="自動生成されます"
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-gray-50"
                      required
                      readOnly
                    />
                    <p className="mt-1 text-xs text-gray-600">
                      フォーマット: YYYYMMDDSSCC
                    </p>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      請求日 <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="date"
                      value={formData.billingDate}
                      onChange={(e) => handleInputChange('billingDate', e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      required
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      支払期限
                    </label>
                    <input
                      type="date"
                      value={formData.dueDate}
                      onChange={(e) => handleInputChange('dueDate', e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>
              </div>

              {/* 請求項目セクション */}
              <div className="mb-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-medium text-gray-900">請求項目</h3>
                  <button
                    type="button"
                    onClick={addBillingItem}
                    className="px-3 py-1 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                  >
                    項目追加
                  </button>
                </div>
                
                <div className="space-y-4">
                  {formData.items.map((item, index) => (
                    <div key={item.id} className="border rounded-lg p-4">
                      <div className="flex items-center justify-between mb-3">
                        <h4 className="font-medium text-gray-900">項目 {index + 1}</h4>
                        {formData.items.length > 1 && (
                          <button
                            type="button"
                            onClick={() => removeBillingItem(item.id)}
                            className="text-red-600 hover:text-red-800 text-sm"
                          >
                            削除
                          </button>
                        )}
                      </div>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            摘要 <span className="text-red-500">*</span>
                          </label>
                          <input
                            type="text"
                            value={item.summary}
                            onChange={(e) => updateBillingItem(item.id, 'summary', e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            placeholder="作業内容を入力"
                            required
                          />
                        </div>
                        
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            単価 <span className="text-red-500">*</span>
                          </label>
                          <input
                            type="number"
                            value={item.unitPrice}
                            onChange={(e) => updateBillingItem(item.id, 'unitPrice', Number(e.target.value))}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            placeholder="0"
                            required
                          />
                        </div>
                        
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            数量 <span className="text-red-500">*</span>
                          </label>
                          <input
                            type="number"
                            value={item.quantity}
                            onChange={(e) => updateBillingItem(item.id, 'quantity', Number(e.target.value))}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            placeholder="1"
                            required
                          />
                        </div>
                        
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            金額
                          </label>
                          <input
                            type="text"
                            value={formatCurrency(calculateItemAmount(item))}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
                            readOnly
                          />
                        </div>
                      </div>
                      
                      <div className="mt-4">
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          備考
                        </label>
                        <textarea
                          value={item.remarks}
                          onChange={(e) => updateBillingItem(item.id, 'remarks', e.target.value)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                          rows={2}
                          placeholder="備考があれば入力"
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* 税区分・合計セクション */}
              <div className="mb-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">税区分・合計</h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      消費税率 (%)
                    </label>
                    <input
                      type="number"
                      value={formData.taxRate}
                      onChange={(e) => handleInputChange('taxRate', Number(e.target.value))}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      min="0"
                      max="100"
                    />
                  </div>
                </div>
                
                <div className="border rounded-lg p-4 bg-gray-50">
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-gray-600">小計:</span>
                      <span className="font-medium">{formatCurrency(calculateSubtotal())}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">消費税 ({formData.taxRate}%):</span>
                      <span className="font-medium">{formatCurrency(calculateTaxAmount())}</span>
                    </div>
                    <div className="flex justify-between text-lg font-semibold border-t pt-2">
                      <span className="text-gray-900">合計:</span>
                      <span className="text-blue-600">{formatCurrency(calculateTotalAmount())}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* 備考セクション */}
              <div className="mb-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">備考</h3>
                <textarea
                  value={formData.notes}
                  onChange={(e) => handleInputChange('notes', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  rows={4}
                  placeholder="請求書に関する備考があれば入力してください"
                />
              </div>

              {/* アクションボタン */}
              <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                >
                  キャンセル
                </button>
                <button
                  type="button"
                  onClick={() => setShowFinalConfirm(true)}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                  確定
                </button>
              </div>
            </div>
          )}

          {/* メール内容タブ */}
          {activeTab === 'email' && (
            <div className="space-y-6">
              {/* メール設定 */}
              <div className="border rounded-lg p-4 mb-6">
                <h3 className="font-medium text-gray-900 mb-3">メール設定</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      件名 <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.emailContent.subject}
                      onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, subject: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="メール件名を入力"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      宛先 <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="email"
                      value={formData.emailContent.to}
                      onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, to: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="メールアドレスを入力"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      CC
                    </label>
                    <input
                      type="email"
                      value={formData.emailContent.cc}
                      onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, cc: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="CCメールアドレスを入力"
                    />
                  </div>
                </div>
              </div>

              {/* メール本文 */}
              <div className="border rounded-lg p-4">
                <h3 className="font-medium text-gray-900 mb-3">メール本文</h3>
                <textarea
                  value={formData.emailContent.body}
                  onChange={(e) => handleInputChange('emailContent', { ...formData.emailContent, body: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  rows={8}
                  placeholder="メール本文を入力"
                  required
                />
              </div>

              {/* アクションボタン */}
              <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                <button
                  type="button"
                  onClick={() => setActiveTab('billing')}
                  className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                >
                  戻る
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setShowFinalConfirm(true);
                  }}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                  確定
                </button>
              </div>
            </div>
          )}
        </form>
      </div>

      {/* 最終確認モーダル */}
      {showFinalConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full mx-4">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-semibold text-gray-900">経理申請確認</h2>
                <button
                  onClick={() => setShowFinalConfirm(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="px-6 py-4">
              <div className="space-y-6">
                {/* 請求書情報 */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">請求書情報</h3>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="text-gray-600">請求書番号:</span>
                      <span className="ml-2 font-medium">{formData.billingNumber}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">案件名:</span>
                      <span className="ml-2 font-medium">{formData.projectName}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">クライアント:</span>
                      <span className="ml-2 font-medium">{formData.clientName}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">請求金額:</span>
                      <span className="ml-2 font-medium">{formatCurrency(calculateTotalAmount())}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">申請者:</span>
                      <span className="ml-2 font-medium">{getCurrentUser().name}</span>
                    </div>
                    <div>
                      <span className="text-gray-600">申請日:</span>
                      <span className="ml-2 font-medium">{new Date().toLocaleDateString('ja-JP')}</span>
                    </div>
                  </div>
                </div>

                {/* 申請者コメント */}
                <div className="border rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-3">申請者コメント</h3>
                  <textarea
                    value={applicantComment}
                    onChange={(e) => setApplicantComment(e.target.value)}
                    placeholder="申請に関するコメントがあれば入力してください（任意）"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    rows={3}
                  />
                </div>

                {/* アクションボタン */}
                <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={() => setShowFinalConfirm(false)}
                    className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
                  >
                    キャンセル
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const billingData = {
                        ...formData,
                        totalAmount: calculateTotalAmount(),
                        subtotal: calculateSubtotal(),
                        taxAmount: calculateTaxAmount(),
                        items: formData.items.map(item => ({
                          ...item,
                          amount: calculateItemAmount(item)
                        })),
                        emailContent: generateEmailContent(),
                        applicantComment: applicantComment,
                        appliedAt: new Date().toISOString(),
                        appliedBy: getCurrentUser().name
                      };
                      
                      if (onBillingApplicationComplete) {
                        onBillingApplicationComplete(billingData);
                      }
                      
                      setShowFinalConfirm(false);
                      onClose();
                    }}
                    className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors"
                  >
                    請求を確定して経理申請
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
} 